name: browser build
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4 #using this github actions it will checekout all the coede
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run #running the cypress test cases it will install the npm dependencies to catch then and run the cy test cases
        uses: cypress-io/github-action@v6 #this will run all the cy testcases which are available on e2e
         with:
          browser: chrome   